FROM ubuntu:latest
FROM python:3.7

RUN apt-get update
RUN apt-get install -y ffmpeg

RUN python -m pip install pipenv

WORKDIR /app
COPY Pipfile .
COPY Pipfile.lock .

RUN pipenv install -v

COPY moviememes moviememes
COPY movie-meme-config.yaml .
COPY movie-meme-generator.py .
COPY webapp.py .
COPY uwsgi.ini .

ENTRYPOINT ["pipenv", "run", "uwsgi", "--ini", "uwsgi.ini"]